let pets = {
    data: [
        {
            petName: "Zuri",
            image: "https://tinyurl.com/yxtw4vvd",
            description: "An amazing and playful dog",
            age: "Young",
            breed: "Poodle",
            size: "Medium",
            gender: "Female", 
            shelter: {
                name: "Happy Paws Shelter",
                place: "Panjim, Goa",
                phone: "123-456-7890",
            },
            volunteer: {
                id: "V001",
                name: "Alice Smith",
            },
            category: "Dog",
        },
        {
            petName: "Koko",
            image: "https://tinyurl.com/5hx2wtp9",
            description: "Very obedient and well trained",
            age: "Adult",
            breed: "Dachshund",
            size: "Large",
            gender: "Male",
            shelter: {
                name: "The Pet Store",
                place: "Mumbai, Maharashtra",
                phone: "123-456-7890",
            },
            volunteer: {
                id: "V002",
                name: "Bob Johnson",
            },
            category: "Dog",
        },
        {
            petName: "Neema",
            image: "https://tinyurl.com/2p9sc5pa",
            description: "Loves playing fetch and always down for food",
            age: "3 months",
            breed: "Bernese Mountain Dog", 
            size: "Small",
            gender: "Female", 
            shelter: {
                name: "Paws and Claws Rescue",
                place: "Kannur, Kerala",
                phone: "123-456-7890",
            },
            volunteer: {
                id: "V003",
                name: "Carol White",
            },
            category: "Dog",
        },
        {
            petName: "Azizi",
            image: "https://tinyurl.com/ycycrnx2",
            description: "Best companion ever. Very lovable",
            age: "Young",
            breed: "Corgi",
            size: "Medium",
            gender: "Male", 
            shelter: {
                name: "Fur Friends",
                place: "Pune, Maharashtra",
                phone: "123-456-7890",
            },
            volunteer: {
                id: "V004",
                name: "David Brown",
            },
            category: "Dog",
        },
        {
            petName: "Amani",
            image: "https://tinyurl.com/2p9eu6ka",
            description: "Very affectionate and playful",
            age: "Young",
            breed: "Shih Tzu",
            size: "Medium",
            gender: "Female", 
            shelter: {
                name: "Wag House",
                place: "Nitte, Karnataka",
                phone: "123-456-7890",
            },
            volunteer: {
                id: "V005",
                name: "Eve Davis",
            },
            category: "Dog",
        },
        {
            petName: "Hasif",
            image: "https://tinyurl.com/2539p6ey",
            description: "Good with children and very affectionate",
            age: "Young",
            breed: "Golden Retriever",
            size: "Large",
            gender: "Male", 
            shelter: {
                name: "Paws Place",
                place: "Mangalore, Karnataka",
                phone: "123-456-7890",
            },
            volunteer: {
                id: "V006",
                name: "Frank Miller",
            },
            category: "Dog",
        },
    ],
};
